### PR TITLE
Code Buddy - Header

### LINKED ISSUE #2: [1pt] Create website header with empty nav
Navs will be added after Components were created

### PR DESCRIPTION
**Pull request by Donard97**
**I opened this PR to review my project if it is as requested 👀** 

### Project requirements that are done:

- Create empty nav ✔️ 
- Add style to nav ✔️ 

<hr>

Feel free to review my project 👀 and if you have any questions please ask me. 💪

### CODE REVIEW

**Review by ahzia — CHANGES_REQUESTED** [review]
Hi @Donard97,

Good job so far!
There are some issues that you still need to work on!

not so close

## Required Changes ♻️

- Add the Profile Avatar on the right side of the header with a dropdown for Profile and Sign in, Signout.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Review by ahzia — APPROVED** [review]
# STATUS: APROVED :green_circle: :clap: 

Hello @Donard97 , 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

well-1

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by Donard97** [comment]
> # STATUS: APROVED 🟢 👏
> Hello @Donard97 , Your project is complete! There is nothing else to say other than... Great job 👏 Congratulations! 🎉
> 
> Now you can merge this branch and move on 🥇 HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES 🤞 🍀
> 
> well-1
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by Donard97** [comment]
@ahzia Thank you for approving my project!

**Pull request merged**
